### ISSUE TITLE
compilation error with QB64PE 3.11.0

### ISSUE THREAD

**Issue by RetroNick2020** [a740g/raylib-64#4]
is this broken in QB64PE 3.11.0?

**Comment by a740g** [comment]
Thanks for reporting. Yes, it was broken due to some C defines I committed to the QB64-PE source. I've made and pushed the necessary changes now so that those are not duplicated in raylib-64 anymore. If you download the latest repo zip that should have the fix included.

**Comment by RetroNick2020** [comment]
thats great! thank you
