### ISSUE TITLE
Fails to Run on later versions of QB64pe

### ISSUE THREAD

**Issue by mechatronic3000** [a740g/raylib-64#5]
It appears to broken with QB64pe v3.10 and v3.11.

It compiles with 3.10, but does not run. It wont compile with 3.11.

I'm running Linux Mint 21.2

Here is the compile log for 3.11

`g++  -no-pie -w -std=gnu++14 -DFREEGLUT_STATIC -I./internal/c/libqb/include -I./internal/c/parts/core/src/ -I./internal/c/parts/core/glew/include/ -DDEPENDENCY_CONSOLE_ONLY -DDEPENDENCY_NO_SOCKETS -DDEPENDENCY_NO_PRINTER -DDEPENDENCY_NO_ICON -DDEPENDENCY_NO_SCREENIMAGE internal/c/libqb.cpp -c -o internal/c/libqb_make_001000000.o
g++  -no-pie -w -std=gnu++14 -DFREEGLUT_STATIC -I./internal/c/libqb/include -I./internal/c/parts/core/src/ -I./internal/c/parts/core/glew/include/ -DDEPENDENCY_CONSOLE_ONLY -DDEPENDENCY_NO_SOCKETS -DDEPENDENCY_NO_PRINTER -DDEPENDENCY_NO_ICON -DDEPENDENCY_NO_SCREENIMAGE internal/c/qbx.cpp -c -o internal/c/qbx.o
g++ -O2  -no-pie -w -std=gnu++14 -DFREEGLUT_STATIC -I./internal/c/libqb/include -I./internal/c/parts/core/src/ -I./internal/c/parts/core/glew/include/ -DDEPENDENCY_CONSOLE_ONLY -DDEPENDENCY_NO_SOCKETS -DDEPENDENCY_NO_PRINTER -DDEPENDENCY_NO_ICON -DDEPENDENCY_NO_SCREENIMAGE -Wall internal/c/libqb/src/threading.cpp -c -o internal/c/libqb/src/threading.o
g++ -O2  -no-pie -w -std=gnu++14 -DFREEGLUT_STATIC -I./internal/c/libqb/include -I./internal/c/parts/core/src/ -I./internal/c/parts/core/glew/include/ -DDEPENDENCY_CONSOLE_ONLY -DDEPENDENCY_NO_SOCKETS -DDEPENDENCY_NO_PRINTER -DDEPENDENCY_NO_ICON -DDEPENDENCY_NO_SCREENIMAGE -Wall internal/c/libqb/src/buffer.cpp -c -o internal/c/libqb/src/buffer.o
g++ -O2  -no-pie -w -std=gnu++14 -DFREEGLUT_STATIC -I./internal/c/libqb/include -I./internal/c/parts/core/src/ -I./internal/c/parts/core/glew/include/ -DDEPENDENCY_CONSOLE_ONLY -DDEPENDENCY_NO_SOCKETS -DDEPENDENCY_NO_PRINTER -DDEPENDENCY_NO_ICON -DDEPENDENCY_NO_SCREENIMAGE -Wall internal/c/libqb/src/filepath.cpp -c -o internal/c/libqb/src/filepath.o
In file included from internal/c/qbx.cpp:2:
internal/c/common.h:97:21: error: expected identifier before ‘-’ token
   97 | #    define QB_TRUE -1
      |                     ^
/mnt/LocalNAS4/LocalNAS/QbasicPrograms/raylib-64/include/raylib.h:19:5: note: in expansion of macro ‘QB_TRUE’
   19 |     QB_TRUE = -1,
      |     ^~~~~~~
internal/c/common.h:97:21: error: expected ‘}’ before ‘-’ token
   97 | #    define QB_TRUE -1
      |                     ^
/mnt/LocalNAS4/LocalNAS/QbasicPrograms/raylib-64/include/raylib.h:19:5: note: in expansion of macro ‘QB_TRUE’
   19 |     QB_TRUE = -1,
      |     ^~~~~~~
In file included from internal/c/../temp/regsf.txt:1,
                 from internal/c/qbx.cpp:1105:
/mnt/LocalNAS4/LocalNAS/QbasicPrograms/raylib-64/include/raylib.h:18:1: note: to match this ‘{’
   18 | {
      | ^
In file included from internal/c/qbx.cpp:2:
internal/c/common.h:97:21: error: expected unqualified-id before ‘-’ token
   97 | #    define QB_TRUE -1
      |                     ^
/mnt/LocalNAS4/LocalNAS/QbasicPrograms/raylib-64/include/raylib.h:19:5: note: in expansion of macro ‘QB_TRUE’
   19 |     QB_TRUE = -1,
      |     ^~~~~~~
In file included from internal/c/../temp/regsf.txt:1,
                 from internal/c/qbx.cpp:1105:
/mnt/LocalNAS4/LocalNAS/QbasicPrograms/raylib-64/include/raylib.h:21:1: error: expected declaration before ‘}’ token
   21 | };
      | ^
In file included from internal/c/qbx.cpp:2:
/mnt/LocalNAS4/LocalNAS/QbasicPrograms/raylib-64/include/raylib.h: In function ‘qb_bool __init_raylib()’:
internal/c/common.h:97:22: error: invalid conversion from ‘int’ to ‘qb_bool’ [-fpermissive]
   97 | #    define QB_TRUE -1
      |                      ^
      |                      |
      |                      int
/mnt/LocalNAS4/LocalNAS/QbasicPrograms/raylib-64/include/raylib.h:1428:16: note: in expansion of macro ‘QB_TRUE’
1428 |         return QB_TRUE;
      |                ^~~~~~~
internal/c/common.h:96:22: error: invalid conversion from ‘int’ to ‘qb_bool’ [-fpermissive]
   96 | #    define QB_FALSE 0
      |                      ^
      |                      |
      |                      int
/mnt/LocalNAS4/LocalNAS/QbasicPrograms/raylib-64/include/raylib.h:1446:24: note: in expansion of macro ‘QB_FALSE’
1446 |                 return QB_FALSE;
      |                        ^~~~~~~~
internal/c/common.h:96:22: error: invalid conversion from ‘int’ to ‘qb_bool’ [-fpermissive]
   96 | #    define QB_FALSE 0
      |                      ^
      |                      |
      |                      int
/mnt/LocalNAS4/LocalNAS/QbasicPrograms/raylib-64/include/raylib.h:1979:16: note: in expansion of macro ‘QB_FALSE’
1979 |         return QB_FALSE;
      |                ^~~~~~~~
internal/c/common.h:97:22: error: invalid conversion from ‘int’ to ‘qb_bool’ [-fpermissive]
   97 | #    define QB_TRUE -1
      |                      ^
      |                      |
      |                      int
/mnt/LocalNAS4/LocalNAS/QbasicPrograms/raylib-64/include/raylib.h:1986:12: note: in expansion of macro ‘QB_TRUE’
1986 |     return QB_TRUE;
      |            ^~~~~~~
make: *** [Makefile:388: internal/c/qbx.o] Error 1
make: *** Waiting for unfinished jobs....`

**Comment by a740g** [comment]
I thought I had fixed this for `3.11`. In fact, I set the minimum required version to `3.11` now because of some changes I made on the QB64-PE side.

See the commits here:
https://github.com/a740g/raylib-64/commits/master/

I suspect you must be on an older version of the master branch. Can you sync the latest from the repo and try again?

**Comment by a740g** [comment]
Fixed in https://github.com/a740g/raylib-64/commit/5cb1dca674eb75eafaa7e1ab5b50947013ad1f62.
